name       : woff2
version    : 1.0.2
release    : 2
source     :
    - https://github.com/google/woff2/archive/v1.0.2.tar.gz : add272bb09e6384a4833ffca4896350fdb16e0ca22df68c0384773c67a175594
license    : MIT
component  : multimedia.graphics
summary    : Woff utilities for compression and decompression
description: |
    Woff utilities for compression and decompression
builddeps   :
    - pkgconfig(libbrotlidec)
setup      : |
    %patch -p1 < $pkgfiles/0001-Install-binaries-always.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
