name       : woff2
version    : 186 # git rev-list HEAD --count
release    : 1
source     :
    - git|https://github.com/google/woff2.git : aa283a500aeb655834d77f3cf9cf1b093b0b4389
license    : Apache-2.0
component  : multimedia.graphics
summary    : Woff utilities for compression and decompression
description: |
    Woff utilities for compression and decompression
build      : |
    %make all
install    : |
    install -dm00755 $installdir/usr/bin
    install -Dm00755 $workdir/woff2_{compress,decompress,info} $installdir/usr/bin/
